from st_supabase_connection import SupabaseConnection

st_supabase_client = st.connection(
    name="remarkable",
    type=SupabaseConnection,
    ttl=None,
    url="https://inxprkvrphodhgwbijwa.supabase.co", # not needed if provided as a streamlit secret
    key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlueHBya3ZycGhvZGhnd2JpandhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDg1NDg1MDUsImV4cCI6MjAyNDEyNDUwNX0.dclk5tp_ylpELV84_bd9dxhzcKjAHtti6qInojcRyxU", # not needed if provided as a streamlit secret
)
